import CKChickenBiryani from "../assets/images/ck-chicken-biryani.png";
import CKKodiVepudu from "../assets/images/ck-kodi-vepudu.png";
import CKChickenCurry from "../assets/images/ck-chicken-curry.png";
import CKChickenPakora from "../assets/images/ck-chicken-pakora.png";
import CKMuttonBiryani from "../assets/images/ck-mutton-biryani.png";
import CKEggBiryani from "../assets/images/ck-egg-biryani.png";
import CKVegBiryani from "../assets/images/ck-veg-biryani.png";
import CKMuttonCurry from "../assets/images/ck-mutton-curry.png";
import CKEggCurry from "../assets/images/ck-egg-curry.png";
import CKPaneerButterMasala from "../assets/images/ck-paneer-butter-masala.png";
import CKKodiIguru from "../assets/images/ck-kodi-iguru.png";
import CKChicken65 from "../assets/images/ck-chicken-65.png";
import CKMuttonFry from "../assets/images/ck-mutton-fry.png";
import CKChickenMajestic from "../assets/images/ck-chicken-majestic.png";
import CKChickenLollipop from "../assets/images/ck-chicken-lollipop.png";
import CKEggPakora from "../assets/images/ck-egg-pakora.png";
import CKChickenFriedRice from "../assets/images/ck-chicken-fried-rice.png";
import CKEggFriedRice from "../assets/images/ck-egg-fried-rice.png";
import CKBiryaniCombo from "../assets/images/ck-biryani-combo.png";
import CKFamilyFeast from "../assets/images/ck-family-feast.png";
import CKSnackPartyBox from "../assets/images/ck-snack-party-box.png";
import CKCurd from "../assets/images/curd.png";
import CKSweetPaan from "../assets/images/sweet-paan.png";
import CKGulabJamun from "../assets/images/gulab-jamun.png";
import CKSprite from "../assets/images/sprite.png";
import CKThumsUp from "../assets/images/thums-up.png";
import CKVanillaIceCream from "../assets/images/vanilla-ice-cream.png";
import CKDoubleKaMeetha from "../assets/images/double-ka-meetha.png";
import CKThickCurd from "../assets/images/thick-curd.png";

export const CLOUD_KITCHEN_CATEGORIES = [
  { id: 'all', label: 'All', emoji: '🍽️' },
  { id: 'biryani', label: 'Biryani', emoji: '🍚' },
  { id: 'main-course', label: 'Main Course', emoji: '🍛' },
  { id: 'starters', label: 'Starters', emoji: '🍗' },
  { id: 'snacks', label: 'Snacks', emoji: '🥘' },
  { id: 'rice-items', label: 'Rice Items', emoji: '🍚' },
  { id: 'combos', label: 'Combos', emoji: '🎁' },
];

export const CLOUD_KITCHEN_DISHES = [
  // ── Biryani ───────────────────────────
  {
    id: 'ck-1',
    name: 'Chicken Biryani',
    teluguName: 'చికెన్ బిర్యానీ',
    hindiName: 'चिकन बिरयानी',
    price: 199,
    tag: '🏆 Best Seller',
    time: '35 min',
    rating: '4.9',
    img: CKChickenBiryani,
    description: 'Our signature Warangal-style Chicken Biryani is slow-cooked with hand-pounded spices, fragrant basmati rice, and tender chicken pieces. Each grain is infused with authentic flavors passed down through generations. Served with raita and mirchi ka salan.',
    servingSize: 'Serves 1-2',
    calories: '~550 kcal',
    spiceLevel: 'Medium',
    category: 'biryani',
    ingredients: ['Basmati Rice', 'Chicken', 'Onions', 'Yogurt', 'Mint', 'Saffron', 'Whole Spices'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-5',
    name: 'Mutton Biryani',
    teluguName: 'మటన్ బిర్యానీ',
    hindiName: 'मटन बिरयानी',
    price: 299,
    tag: '👑 Premium',
    time: '50 min',
    rating: '4.9',
    img: CKMuttonBiryani,
    description: 'Slow-cooked Warangal-style Mutton Biryani with succulent bone-in goat meat, layered with aged basmati rice, fried onions, and aromatic dum masala. Sealed and cooked on slow fire for maximum flavor. Served with mirchi ka salan and raita.',
    servingSize: 'Serves 1-2',
    calories: '~650 kcal',
    spiceLevel: 'Medium',
    category: 'biryani',
    ingredients: ['Basmati Rice', 'Mutton', 'Fried Onions', 'Yogurt', 'Mint', 'Saffron', 'Dum Masala'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-6',
    name: 'Egg Biryani',
    teluguName: 'ఎగ్ బిర్యానీ',
    hindiName: 'अंडा बिरयानी',
    price: 149,
    tag: '💛 Value Pick',
    time: '30 min',
    rating: '4.7',
    img: CKEggBiryani,
    description: 'Aromatic Egg Biryani made with perfectly boiled eggs simmered in a rich masala gravy, layered with fragrant basmati rice and finished with dum cooking. An affordable yet deeply satisfying homestyle meal.',
    servingSize: 'Serves 1-2',
    calories: '~450 kcal',
    spiceLevel: 'Medium',
    category: 'biryani',
    ingredients: ['Basmati Rice', 'Eggs', 'Onions', 'Tomatoes', 'Mint', 'Green Chillies', 'Whole Spices'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-13',
    name: 'Veg Biryani',
    teluguName: 'వెజ్ బిర్యానీ',
    hindiName: 'वेज बिरयानी',
    price: 149,
    tag: '🌿 Pure Veg',
    time: '30 min',
    rating: '4.6',
    img: CKVegBiryani,
    description: 'Fragrant Veg Biryani loaded with seasonal vegetables, paneer cubes, and aromatic spices. Layered with premium basmati rice and cooked on slow dum for maximum flavor. A wholesome vegetarian feast.',
    servingSize: 'Serves 1-2',
    calories: '~420 kcal',
    spiceLevel: 'Mild',
    category: 'biryani',
    ingredients: ['Basmati Rice', 'Mixed Vegetables', 'Paneer', 'Onions', 'Mint', 'Saffron', 'Whole Spices'],
    isVeg: true,
    isAvailable: true,
  },

  // ── Main Course ───────────────────────
  {
    id: 'ck-3',
    name: 'Chicken Curry',
    teluguName: 'చికెన్ కూర',
    hindiName: 'चिकन करी',
    price: 179,
    tag: '❤️ Fan Fav',
    time: '30 min',
    rating: '4.9',
    img: CKChickenCurry,
    description: 'Rich, aromatic Chicken Curry made with freshly ground spices and a tomato-onion base cooked in the authentic Warangal style. The gravy is thick, flavorful, and goes perfectly with steamed rice or fresh rotis. A comfort dish loved by families across Telangana.',
    servingSize: 'Serves 2',
    calories: '~480 kcal',
    spiceLevel: 'Medium',
    category: 'main-course',
    ingredients: ['Chicken', 'Tomatoes', 'Onions', 'Ginger-Garlic Paste', 'Coriander', 'Chilli Powder'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-7',
    name: 'Mutton Curry',
    teluguName: 'మటన్ కూర',
    hindiName: 'मटन करी',
    price: 279,
    tag: '👑 Premium',
    time: '45 min',
    rating: '4.9',
    img: CKMuttonCurry,
    description: 'Authentic Telangana-style Mutton Curry slow-cooked with bone-in goat meat in a rich, spicy gravy of roasted spices, onions, and tomatoes. The meat falls off the bone. Best enjoyed with hot steamed rice or soft rotis.',
    servingSize: 'Serves 2',
    calories: '~560 kcal',
    spiceLevel: 'Hot',
    category: 'main-course',
    ingredients: ['Mutton', 'Onions', 'Tomatoes', 'Coriander Seeds', 'Red Chillies', 'Curry Leaves', 'Coconut'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-8',
    name: 'Egg Curry',
    teluguName: 'ఎగ్ కూర',
    hindiName: 'अंडा करी',
    price: 129,
    tag: '💛 Value Pick',
    time: '20 min',
    rating: '4.7',
    img: CKEggCurry,
    description: 'Homestyle Egg Curry with perfectly boiled eggs in a tangy tomato-onion gravy seasoned with mustard seeds, curry leaves, and Warangal special masala. Simple, hearty, and full of homemade flavor.',
    servingSize: 'Serves 2',
    calories: '~350 kcal',
    spiceLevel: 'Medium',
    category: 'main-course',
    ingredients: ['Eggs', 'Tomatoes', 'Onions', 'Mustard Seeds', 'Curry Leaves', 'Turmeric'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-14',
    name: 'Paneer Butter Masala',
    teluguName: 'పన్నీర్ బటర్ మసాలా',
    hindiName: 'पनीर बटर मसाला',
    price: 169,
    tag: '🌿 Pure Veg',
    time: '25 min',
    rating: '4.8',
    img: CKPaneerButterMasala,
    description: 'Soft paneer cubes simmered in a velvety, mildly spiced tomato-cashew gravy with a touch of cream and butter. A rich vegetarian main course that pairs beautifully with naan or jeera rice.',
    servingSize: 'Serves 2',
    calories: '~420 kcal',
    spiceLevel: 'Mild',
    category: 'main-course',
    ingredients: ['Paneer', 'Tomatoes', 'Cashews', 'Butter', 'Cream', 'Fenugreek Leaves', 'Garam Masala'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-15',
    name: 'Kodi Iguru',
    teluguName: 'కోడి ఇగురు',
    hindiName: 'चिकन भुर्जी',
    price: 189,
    tag: '🌶️ Spicy',
    time: '25 min',
    rating: '4.8',
    img: CKChicken65,
    description: 'Fiery Telangana-style Kodi Iguru — a semi-dry chicken preparation with freshly pounded spices, onions, and green chillies. Cooked with minimal oil for an intense, rustic flavor. A must-try regional specialty.',
    servingSize: 'Serves 2',
    calories: '~420 kcal',
    spiceLevel: 'Hot',
    category: 'main-course',
    ingredients: ['Chicken', 'Onions', 'Green Chillies', 'Ginger-Garlic', 'Cumin', 'Coriander', 'Pepper'],
    isVeg: false,
    isAvailable: true,
  },

  // ── Starters ──────────────────────────
  {
    id: 'ck-2',
    name: 'Kodi Vepudu',
    teluguName: 'కోడి వేపుడు',
    hindiName: 'चिकन फ्राई',
    price: 169,
    tag: '🌶️ Spicy',
    time: '25 min',
    rating: '4.8',
    img: CKKodiVepudu,
    description: 'Crispy, fiery Kodi Vepudu (Chicken Fry) made with country-style masala and fresh curry leaves. Each piece is marinated for hours and shallow-fried to golden perfection. A true Telangana delicacy that pairs perfectly with hot rice or rotis.',
    servingSize: 'Serves 1-2',
    calories: '~450 kcal',
    spiceLevel: 'Hot',
    category: 'starters',
    ingredients: ['Chicken', 'Red Chilli', 'Curry Leaves', 'Garlic', 'Ginger', 'Turmeric'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-9',
    name: 'Chicken 65',
    teluguName: 'చికెన్ 65',
    hindiName: 'चिकन 65',
    price: 179,
    tag: '🔥 Hot Fav',
    time: '20 min',
    rating: '4.8',
    img: CKChicken65,
    description: 'Iconic Chicken 65 — boneless chicken pieces marinated in a fiery blend of red chilli paste, yogurt, and spices, then deep-fried until crispy. Finished with a tempering of curry leaves, green chillies, and garlic. The ultimate South Indian starter.',
    servingSize: 'Serves 1-2',
    calories: '~400 kcal',
    spiceLevel: 'Hot',
    category: 'starters',
    ingredients: ['Chicken', 'Yogurt', 'Red Chilli Paste', 'Corn Flour', 'Curry Leaves', 'Garlic'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-10',
    name: 'Mutton Fry',
    teluguName: 'మటన్ వేపుడు',
    hindiName: 'मटन फ्राई',
    price: 259,
    tag: '👑 Premium',
    time: '35 min',
    rating: '4.9',
    img: CKMuttonFry,
    description: 'Succulent, bone-in mutton pieces dry-roasted with aromatic spices, curry leaves, and a generous helping of freshly cracked pepper. A rich, flavorful Telangana-style dry fry that melts in your mouth.',
    servingSize: 'Serves 1-2',
    calories: '~500 kcal',
    spiceLevel: 'Hot',
    category: 'starters',
    ingredients: ['Mutton', 'Red Chillies', 'Curry Leaves', 'Black Pepper', 'Fennel Seeds', 'Garlic'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-16',
    name: 'Chicken Majestic',
    teluguName: 'చికెన్ మెజెస్టిక్',
    hindiName: 'चिकन मेजेस्टिक',
    price: 189,
    tag: '⭐ Popular',
    time: '25 min',
    rating: '4.8',
    img: CKChickenMajestic,
    description: 'Crispy boneless chicken tossed with bell peppers, onions, and a sweet-spicy sauce. A Hyderabadi street food legend, now in your home kitchen. Crunchy outside, juicy inside.',
    servingSize: 'Serves 1-2',
    calories: '~430 kcal',
    spiceLevel: 'Medium',
    category: 'starters',
    ingredients: ['Chicken', 'Bell Peppers', 'Onions', 'Corn Flour', 'Soy Sauce', 'Chilli Sauce', 'Garlic'],
    isVeg: false,
    isAvailable: true,
  },

  // ── Snacks ────────────────────────────
  {
    id: 'ck-4',
    name: 'Chicken Pakora',
    teluguName: 'చికెన్ పకోడా',
    hindiName: 'चिकन पकोड़ा',
    price: 149,
    tag: '⚡ Quick Bite',
    time: '20 min',
    rating: '4.7',
    img: CKChickenPakora,
    description: 'Crunchy, golden Chicken Pakoras marinated in a blend of Warangal spices and gram flour, deep-fried to crispy perfection. These bite-sized treats are the perfect evening snack or party starter. Served with green chutney and onion rings.',
    servingSize: 'Serves 1-2',
    calories: '~380 kcal',
    spiceLevel: 'Medium',
    category: 'snacks',
    ingredients: ['Chicken', 'Gram Flour', 'Rice Flour', 'Green Chillies', 'Ginger', 'Egg'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-11',
    name: 'Chicken Lollipop',
    teluguName: 'చికెన్ లాలీపాప్',
    hindiName: 'चिकन लॉलीपॉप',
    price: 169,
    tag: '🎉 Party Fav',
    time: '25 min',
    rating: '4.8',
    img: CKChickenLollipop,
    description: 'Crispy fried Chicken Lollipops made from tender wing joints, marinated in a spicy batter and deep-fried until golden. Served with schezwan sauce. A party favorite that disappears in minutes!',
    servingSize: 'Serves 2-3',
    calories: '~420 kcal',
    spiceLevel: 'Medium',
    category: 'snacks',
    ingredients: ['Chicken Wings', 'Corn Flour', 'Maida', 'Ginger-Garlic Paste', 'Chilli Flakes', 'Egg'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-12',
    name: 'Egg Pakora',
    teluguName: 'ఎగ్ పకోడా',
    hindiName: 'अंडा पकोड़ा',
    price: 99,
    tag: '💛 Budget',
    time: '15 min',
    rating: '4.6',
    img: CKEggPakora,
    description: 'Boiled eggs coated in a spiced gram flour batter, deep-fried to a golden crisp. A simple, satisfying Telangana tea-time snack loved by all age groups. Served with tomato ketchup.',
    servingSize: 'Serves 1-2',
    calories: '~280 kcal',
    spiceLevel: 'Mild',
    category: 'snacks',
    ingredients: ['Eggs', 'Gram Flour', 'Rice Flour', 'Red Chilli Powder', 'Ajwain', 'Salt'],
    isVeg: false,
    isAvailable: true,
  },

  // ── Rice Items ────────────────────────
  {
    id: 'ck-17',
    name: 'Chicken Fried Rice',
    teluguName: 'చికెన్ ఫ్రైడ్ రైస్',
    hindiName: 'चिकन फ्राइड राइस',
    price: 169,
    tag: '⚡ Quick Bite',
    time: '20 min',
    rating: '4.7',
    img: CKChickenFriedRice,
    description: 'Indo-Chinese style Chicken Fried Rice with juicy chicken pieces, crunchy vegetables, and aromatic soy-garlic seasoning. Wok-tossed on high flame for smoky flavor. A crowd pleaser.',
    servingSize: 'Serves 1-2',
    calories: '~480 kcal',
    spiceLevel: 'Medium',
    category: 'rice-items',
    ingredients: ['Rice', 'Chicken', 'Egg', 'Spring Onions', 'Soy Sauce', 'Garlic', 'Vegetables'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-18',
    name: 'Egg Fried Rice',
    teluguName: 'ఎగ్ ఫ్రైడ్ రైస్',
    hindiName: 'अंडा फ्राइड राइस',
    price: 129,
    tag: '💛 Value Pick',
    time: '15 min',
    rating: '4.6',
    img: CKEggFriedRice,
    description: 'Quick and delicious Egg Fried Rice with scrambled eggs, fresh vegetables, and a smoky wok flavor. A perfect weekday meal that is light yet filling.',
    servingSize: 'Serves 1',
    calories: '~400 kcal',
    spiceLevel: 'Mild',
    category: 'rice-items',
    ingredients: ['Rice', 'Eggs', 'Spring Onions', 'Soy Sauce', 'Garlic', 'Mixed Vegetables'],
    isVeg: false,
    isAvailable: true,
  },

  // ── Combos ────────────────────────────
  {
    id: 'ck-19',
    name: 'Biryani + Chicken Fry Combo',
    teluguName: 'బిర్యానీ + చికెన్ ఫ్రై కాంబో',
    hindiName: 'बिरयानी + चिकन फ्राई कॉम्बो',
    price: 329,
    tag: '🎁 Best Value',
    time: '40 min',
    rating: '4.9',
    img: CKBiryaniCombo,
    description: 'Our best-selling combo! Get a full plate of aromatic Chicken Biryani paired with crispy Kodi Vepudu (Chicken Fry). Includes raita and mirchi ka salan. Perfect for a complete feast.',
    servingSize: 'Serves 2',
    calories: '~900 kcal',
    spiceLevel: 'Medium',
    category: 'combos',
    ingredients: ['Chicken Biryani', 'Chicken Fry', 'Raita', 'Mirchi Ka Salan'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-20',
    name: 'Family Feast Combo',
    teluguName: 'ఫ్యామిలీ ఫీస్ట్ కాంబో',
    hindiName: 'फैमिली फीस्ट कॉम्बो',
    price: 599,
    tag: '👨‍👩‍👧‍👦 Family',
    time: '45 min',
    rating: '4.9',
    img: CKFamilyFeast,
    description: 'The ultimate family meal! Includes Chicken Biryani (family pack), Chicken Curry, Chicken Pakora starter, raita, and mirchi ka salan. Feeds 4 people generously. Perfect for weekend family dinners.',
    servingSize: 'Serves 4',
    calories: '~2200 kcal',
    spiceLevel: 'Medium',
    category: 'combos',
    ingredients: ['Chicken Biryani', 'Chicken Curry', 'Chicken Pakora', 'Raita', 'Salan'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-21',
    name: 'Snack Party Box',
    teluguName: 'స్నాక్ పార్టీ బాక్స్',
    hindiName: 'स्नैक पार्टी बॉक्स',
    price: 449,
    tag: '🎉 Party',
    time: '30 min',
    rating: '4.8',
    img: CKSnackPartyBox,
    description: 'A party box loaded with Chicken Pakora, Chicken Lollipop, Chicken 65, and green chutney. Perfect for get-togethers, movie nights, and cricket watch parties. Serves 4-6 people.',
    servingSize: 'Serves 4-6',
    calories: '~1600 kcal',
    spiceLevel: 'Medium',
    category: 'combos',
    ingredients: ['Chicken Pakora', 'Chicken Lollipop', 'Chicken 65', 'Green Chutney', 'Onion Rings'],
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'ck-22',
    name: 'Thick Curd',
    teluguName: 'తాజా పెరుగు',
    hindiName: 'ताजा दही',
    price: 30,
    tag: '🥛 Refreshing',
    time: '10 min',
    rating: '4.8',
    img: CKThickCurd,
    description: 'Thick, creamy, and chilled home-style curd. The perfect accompaniment to pair with our spicy biryanis and curries.',
    servingSize: '1 Cup (250g)',
    calories: '~120 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Milk', 'Active Culture'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-23',
    name: 'Double Ka Meetha',
    teluguName: 'డబుల్ కా మీఠా',
    hindiName: 'डबल का मीठा',
    price: 80,
    tag: '🍯 Royal Sweet',
    time: '15 min',
    rating: '4.9',
    img: CKDoubleKaMeetha,
    description: 'A traditional Hyderabadi bread pudding sweet, fried golden, soaked in saffron and cardamom syrup, topped with rich rabri and dry fruits.',
    servingSize: '1 Bowl',
    calories: '~380 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Bread', 'Milk', 'Saffron', 'Sugar', 'Ghee', 'Cashews', 'Almonds'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-24',
    name: 'Vanilla Ice Cream',
    teluguName: 'వెనిల్లా ఐస్ క్రీమ్',
    hindiName: 'वेनिला आइसक्रीम',
    price: 60,
    tag: '🍨 Chilled Dessert',
    time: '10 min',
    rating: '4.8',
    img: CKVanillaIceCream,
    description: 'Classic rich and creamy vanilla bean ice cream. The perfect dessert to cool down your palate after a spicy meal.',
    servingSize: '1 Cup',
    calories: '~200 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Cream', 'Milk', 'Vanilla Extract', 'Sugar'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-25',
    name: 'Thums Up (750ml)',
    teluguName: 'థమ్స్ అప్',
    hindiName: 'थम्स अप',
    price: 45,
    tag: '🥤 Chilled Soda',
    time: '5 min',
    rating: '4.8',
    img: CKThumsUp,
    description: 'Refreshing and strong carbonated soft drink served ice-cold. Best paired alongside our hot biryanis.',
    servingSize: '750ml Bottle',
    calories: '150 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Carbonated Water', 'Sugar', 'Caffeine'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-26',
    name: 'Gulab Jamun',
    teluguName: 'గులాబ్ జామూన్',
    hindiName: 'गुलाब जामुन',
    price: 50,
    tag: '🍯 Popular Sweet',
    time: '10 min',
    rating: '4.9',
    img: CKGulabJamun,
    description: 'Soft, delicious berry-sized balls made of milk solids, flour, and a leavening agent. These are fried golden brown and soaked in rose-flavored sugar syrup. Traditional and absolutely heavenly.',
    servingSize: '2 Pieces',
    calories: '150 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Koya', 'Paneer', 'Sugar', 'Cardamom', 'Rose Water'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-27',
    name: 'Sprite (750ml)',
    teluguName: 'స్ప్రైట్',
    hindiName: 'स्प्राइट',
    price: 45,
    tag: '🥤 Lemon Soda',
    time: '5 min',
    rating: '4.8',
    img: CKSprite,
    description: 'Crisp, clean, and refreshing lemon-lime carbonated soft drink served ice-cold to soothe your taste buds.',
    servingSize: '750ml Bottle',
    calories: '140 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Carbonated Water', 'Sugar', 'Citric Acid', 'Natural Flavors'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-28',
    name: 'Sweet Paan',
    teluguName: 'మీటా పాన్',
    hindiName: 'मीठा पान',
    price: 25,
    tag: '🍂 Mouth Freshener',
    time: '5 min',
    rating: '4.9',
    img: CKSweetPaan,
    description: 'Traditional Indian mouth freshener and digestive made of betel leaf filled with gulkand, desiccated coconut, fennel seeds, and sweet syrups. Perfect post-meal delight.',
    servingSize: '1 Piece',
    calories: '80 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Betel Leaf', 'Gulkand', 'Fennel Seeds', 'Sweet Syrups', 'Coconut'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-29',
    name: 'Chilled Water Bottle (1L)',
    teluguName: 'మంచినీటి సీసా',
    hindiName: 'पानी की बोतल',
    price: 20,
    tag: '💧 Chilled',
    time: '5 min',
    rating: '4.9',
    img: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    description: 'Chilled mineral water bottle to stay hydrated alongside your hot meal.',
    servingSize: '1 Bottle',
    calories: '0 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Mineral Water'],
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'ck-30',
    name: 'Disposable Plates & Spoons (10Pcs)',
    teluguName: 'డిస్పోజబుల్ ప్లేట్లు',
    hindiName: 'डिस्पोजेबल प्लेटें',
    price: 30,
    tag: '🍽️ Party Ready',
    time: '5 min',
    rating: '4.8',
    img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400',
    description: 'Pack of 10 eco-friendly, biodegradable plates and wooden spoons for hassle-free serving.',
    servingSize: '1 Pack (10 Pcs)',
    calories: '0 kcal',
    spiceLevel: 'Mild',
    category: 'sides',
    ingredients: ['Eco-friendly Plates', 'Wooden Spoons'],
    isVeg: true,
    isAvailable: true,
  },
];
